/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfirmedRouteImport } from './routes/confirmed'
import { Route as OrderRouteImport } from './routes/_order'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderShippingRouteImport } from './routes/_order.shipping'
import { Route as OrderConfigureRouteImport } from './routes/_order.configure'

const ConfirmedRoute = ConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/_order',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderShippingRoute = OrderShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => OrderRoute,
} as any)
const OrderConfigureRoute = OrderConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => OrderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmed': typeof ConfirmedRoute
  '/configure': typeof OrderConfigureRoute
  '/shipping': typeof OrderShippingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmed': typeof ConfirmedRoute
  '/configure': typeof OrderConfigureRoute
  '/shipping': typeof OrderShippingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_order': typeof OrderRouteWithChildren
  '/confirmed': typeof ConfirmedRoute
  '/_order/configure': typeof OrderConfigureRoute
  '/_order/shipping': typeof OrderShippingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/confirmed' | '/configure' | '/shipping'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/confirmed' | '/configure' | '/shipping'
  id:
    | '__root__'
    | '/'
    | '/_order'
    | '/confirmed'
    | '/_order/configure'
    | '/_order/shipping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrderRoute: typeof OrderRouteWithChildren
  ConfirmedRoute: typeof ConfirmedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/confirmed': {
      id: '/confirmed'
      path: '/confirmed'
      fullPath: '/confirmed'
      preLoaderRoute: typeof ConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_order': {
      id: '/_order'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_order/shipping': {
      id: '/_order/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof OrderShippingRouteImport
      parentRoute: typeof OrderRoute
    }
    '/_order/configure': {
      id: '/_order/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof OrderConfigureRouteImport
      parentRoute: typeof OrderRoute
    }
  }
}

interface OrderRouteChildren {
  OrderConfigureRoute: typeof OrderConfigureRoute
  OrderShippingRoute: typeof OrderShippingRoute
}

const OrderRouteChildren: OrderRouteChildren = {
  OrderConfigureRoute: OrderConfigureRoute,
  OrderShippingRoute: OrderShippingRoute,
}

const OrderRouteWithChildren = OrderRoute._addFileChildren(OrderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrderRoute: OrderRouteWithChildren,
  ConfirmedRoute: ConfirmedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
